repos:
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.6
  hooks:
    # - id: bundler-audit
    # - id: check-mailmap
    # - id: fasterer
    # - id: forbid-binary
    # - id: forbid-space-in-indent
    # - id: git-check  # Configure in .gitattributes
    # - id: git-dirty  # Configure in .gitignore
    # - id: markdownlint # Configure in .mdlrc
    # - id: reek
    # - id: require-ascii
    # - id: rubocop
    # - id: script-must-have-extension
    # - id: script-must-not-have-extension
    # - id: shellcheck
    - id: shfmt
      args:
       - -i
       - "2"
